### ISSUE TITLE
Please consider adding extension to OpenVSX Registry

### ISSUE THREAD

**Issue by edomato** [uqbar-project/wollok-highlight-vscode#8]
Hi,

That registry (https://open-vsx.org/about) is an open-source VS Code Registry for extensions.

To add extension, there's a short wiki page for it (https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Doing this, anybody using for example VSCodium (https://vscodium.com/), which is the FOSS version fo VSCode can install the extension from it extension manager.

If I can get some time, maybe I could help and do a pull request for it (if you're interested), but I need first to understand how it works since I'm just pretty new to the Code environment. :smiley: 

Greets

**Comment by fdodino** [comment]
hi @edomato , we've finally released it!

https://open-vsx.org/extension/uqbar/wollok-highlight

**Comment by fdodino** [comment]
Closing issue since I also added some instructions in our wiki.
